### ISSUE TITLE
Kernel error on lab computers

### ISSUE THREAD

**Issue by fediskhakov** [CompEconCourse/CourseMaterials#1]
Kernel error
pops up on a number of computers in the 432 right after opening Jupyter Notebooks

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 547, in write_connection_file
    kernel_name=self.kernel_name
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
    with secure_write(fname) as f:
  File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 102, in secure_write
    with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\TEMP.SPB.013\\AppData\\Roaming\\jupyter\\runtime\\kernel-7d9a8b32-2560-4ea6-909c-cc39d134c190.json'

**Comment by fediskhakov** [comment]
To recreate: Start Julyter Notebook (or Lab) from Anaconda Navigator.
Create new Python 3 notebook.
Kernal error appears on kernal initialization.

**Comment by fediskhakov** [comment]
Machine 1968 does not appear to have the problem,
while most other (including 1903 do)

**Comment by fediskhakov** [comment]
From: Техническая поддержка (Спб) <it-spb@hse.ru>
Date: Wed, Jan 29, 2020 at 11:35 AM
Subject: RE: Запрос на установку дополнительного софта + исправление проблемы в ауд 432
To: Иванова Вера Ивановна <viivanova@hse.ru>, Техническая поддержка (Спб) <it-spb@hse.ru>, fedor.iskhakov@anu.edu.au <fedor.iskhakov@anu.edu.au>
Cc: Гросс Юрий Георгиевич <ygross@hse.ru>

Добрый день.

Проблема создания проекта в Anaconda заключалась во временной учётной записи user, которая у нас используется для студентов. Используйте учётную запись userrts (пароль такой же). У этой записи профиль постоянный, мы проверили, ошибки нет.

Git уже был ранее установлен. Находится в «Пуск».
